Repository d-strobel/gowindows, pull requests merged in 2024-01, with the labels that each got.

#32 Docs/add logo
  README.md
  images/logo/README.md
  images/logo/gowindows-icon.png
  images/logo/gowindows-icon_250.png
Labels: documentation

#33 Refactor/function parameters
  README.md
  windows/local/local_group.go
  windows/local/local_group_acc_test.go
  windows/local/local_group_test.go
  windows/local/local_groupmember.go
  windows/local/local_groupmember_acc_test.go
  windows/local/local_groupmember_test.go
  windows/local/local_user.go
  windows/local/local_user_acc_test.go
  windows/local/local_user_test.go
Labels: enhancement

#35 fix: local.GroupUpdate cannot update empty description
  windows/local/local_group.go
  windows/local/local_group_test.go
Labels: bug

#36 Fix/local user create
  windows/local/local_client.go
  windows/local/local_client_test.go
  windows/local/local_user.go
  windows/local/local_user_test.go
Labels: bug, enhancement
